<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>BallsServer</AssemblyName>
    <RootNamespace>BallsServer.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BallsServer.Core\BallsServer.Core.csproj" />
    <ProjectReference Include="..\BallsServer.Helper\BallsServer.Helper.csproj"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\BallsServer.Presentation\BallsServer.Presentation.csproj" />
    <ProjectReference Include="..\BallsServer.Windows\BallsServer.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="..\..\balls-server-logo.png" Link="Assets\balls-server-logo.png" />
  </ItemGroup>
  <Target Name="CopyBallsServerHelper" AfterTargets="Build">
    <ItemGroup>
      <BallsServerHelperFile Include="..\BallsServer.Helper\bin\$(Configuration)\$(TargetFramework)\BallsServer.Helper.exe" />
      <BallsServerHelperFile Include="..\BallsServer.Helper\bin\$(Configuration)\$(TargetFramework)\BallsServer.Helper.dll" />
      <BallsServerHelperFile Include="..\BallsServer.Helper\bin\$(Configuration)\$(TargetFramework)\BallsServer.Helper.deps.json" />
      <BallsServerHelperFile Include="..\BallsServer.Helper\bin\$(Configuration)\$(TargetFramework)\BallsServer.Helper.runtimeconfig.json" />
    </ItemGroup>
    <Copy SourceFiles="@(BallsServerHelperFile)"
          DestinationFolder="$(OutDir)"
          SkipUnchangedFiles="true" />
  </Target>
</Project>
